name: .NET Build

on:
  push:
    branches:
      - main  # Change this to your default branch name if necessary
  pull_request:
    branches:
      - main  # Change this to your default branch name if necessary

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for .NET Framework projects

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-version: 'latest'

    - name: Restore dependencies
      run: msbuild YourSolution.sln /p:Configuration=Release /t:Restore

    - name: Build
      run: msbuild YourSolution.sln /p:Configuration=Release

    - name: Publish
      run: msbuild YourProject.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=YourPublishProfile.pubxml  # Adjust as necessary

    - name: Deploy
      run: |
        echo "Deploying..."
        # Add your deployment commands here, e.g., FTP, Azure, etc.
